GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/shorten
Content-Type: application/json

{
    "long_url": "https://duplxey.com",
    "alias": "duplxey"
}

###

POST http://127.0.0.1:8000/shorten
Content-Type: application/json

{
    "long_url": "https://back4app.com",
    "alias": "back4app"
}

###

GET http://127.0.0.1:8000/duplxey
Accept: application/json
